import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import Header from './components/Header';
import ListingPage from './pages/ListingPage';
import MapPage from './pages/MapPage';
import LoginPage from './pages/LoginPage';
import SignupPage from './pages/SignupPage';
import { AuthProvider } from './contexts/AuthContext';
import './App.css';
export default function App() {
    return (_jsx(AuthProvider, { children: _jsxs(BrowserRouter, { children: [_jsx(Header, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/rent", element: _jsx(ListingPage, { purpose: "rent" }) }), _jsx(Route, { path: "/sale", element: _jsx(ListingPage, { purpose: "sale" }) }), _jsx(Route, { path: "/map-rent", element: _jsx(MapPage, { purpose: "rent" }) }), _jsx(Route, { path: "/map-sale", element: _jsx(MapPage, { purpose: "sale" }) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/signup", element: _jsx(SignupPage, {}) })] })] }) }));
}
function HomePage() {
    return (_jsxs("div", { className: "home-page", children: [_jsx("section", { className: "hero", children: _jsxs("div", { className: "hero-content", children: [_jsx("h1", { children: "Bienvenue chez Ymmo" }), _jsx("p", { children: "Trouvez votre prochain bien immobilier" })] }) }), _jsx("section", { className: "quick-access", children: _jsxs("div", { className: "container", children: [_jsx("h2", { children: "Que cherchez-vous?" }), _jsxs("div", { className: "access-grid", children: [_jsxs(Link, { to: "/rent", className: "access-card", children: [_jsx("div", { className: "card-icon" }), _jsx("h3", { children: "\u00C0 Louer" }), _jsx("p", { children: "Explorez nos annonces de location" }), _jsx("span", { className: "arrow", children: "\u2192" })] }), _jsxs(Link, { to: "/sale", className: "access-card", children: [_jsx("div", { className: "card-icon" }), _jsx("h3", { children: "\u00C0 Vendre" }), _jsx("p", { children: "D\u00E9couvrez nos propri\u00E9t\u00E9s \u00E0 vendre" }), _jsx("span", { className: "arrow", children: "\u2192" })] }), _jsxs(Link, { to: "/map-rent", className: "access-card", children: [_jsx("div", { className: "card-icon" }), _jsx("h3", { children: "Carte - Location" }), _jsx("p", { children: "Visualisez les biens sur la carte" }), _jsx("span", { className: "arrow", children: "\u2192" })] }), _jsxs(Link, { to: "/map-sale", className: "access-card", children: [_jsx("div", { className: "card-icon" }), _jsx("h3", { children: "Carte - Vente" }), _jsx("p", { children: "Trouvez des biens \u00E0 proximit\u00E9" }), _jsx("span", { className: "arrow", children: "\u2192" })] })] })] }) }), _jsx("section", { className: "features", children: _jsxs("div", { className: "container", children: [_jsx("h2", { children: "Pourquoi Ymmo?" }), _jsxs("div", { className: "features-grid", children: [_jsxs("div", { className: "feature", children: [_jsx("span", { className: "feature-icon", children: "\u2713" }), _jsx("h3", { children: "Filtres Avanc\u00E9s" }), _jsx("p", { children: "Affinez votre recherche avec des crit\u00E8res d\u00E9taill\u00E9s" })] }), _jsxs("div", { className: "feature", children: [_jsx("span", { className: "feature-icon", children: "\u2713" }), _jsx("h3", { children: "Visualisation Cartographique" }), _jsx("p", { children: "Localisez les biens sur une carte interactive" })] }), _jsxs("div", { className: "feature", children: [_jsx("span", { className: "feature-icon", children: "\u2713" }), _jsx("h3", { children: "Avis & Commentaires" }), _jsx("p", { children: "Lisez les retours des autres utilisateurs" })] }), _jsxs("div", { className: "feature", children: [_jsx("span", { className: "feature-icon", children: "\u2713" }), _jsx("h3", { children: "Service Client 24/7" }), _jsx("p", { children: "Nous sommes toujours l\u00E0 pour vous aider" })] })] })] }) })] }));
}
